Update Chocolatine.yml

diff --git a/.github/workflows/Chocolatine.yml b/.github/workflows/Chocolatine.yml
--- a/.github/workflows/Chocolatine.yml
+++ b/.github/workflows/Chocolatine.yml
@@ -11,27 +11,38 @@ on:
   pull_request:
     branches:
     - '*'
+    
+  workflow_dispatch:
+    
 jobs:
 
   job1:
+  
     runs-on: ubuntu-latest
-
-    steps:
-      - name: Compile code
-        run: |
-          make
-      - name: run programme
-        run: |
-          ./mysh
-      - name: Push
-        run: |
-          echo " Succes Compile "
-    if: ${{ job.status == 'success' }}
     
-  job2:
-      needs: job1
-      runs-on: ubuntu-latest
+    steps:
+    
+    - name: Install dependencies      
+      run: |
+        sudo apt-get update
+        sudo apt-get install -y nodejs
+        
+    - name: Checkout code
+      uses: actions/checkout@v2
+      with:
+        repository: ${{ env.MIRROR_URL }}
+        ssh-key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
+    
+    - name: Build code
+      run: |
+        make
       
-      steps:
-        - name: coding-style-check
-          run : coding-style.sh . .
+    - name: Verify build
+      run: |
+        if [ $? -eq 0 ]; then
+          echo "Build succeeded!"
+        else
+          echo "Build failed!"
+          exit 1
+        fi
+
