Update Chocolatine.yml

diff --git a/.github/workflows/Chocolatine.yml b/.github/workflows/Chocolatine.yml
--- a/.github/workflows/Chocolatine.yml
+++ b/.github/workflows/Chocolatine.yml
@@ -37,4 +37,34 @@ jobs:
           echo "Build failed!"
           exit 1
         fi
+  job2:
+  
+    needs: job1
+    runs-on: ubuntu-latest
+    container:
+      image: ghcr.io/epitech/coding-style-checker:latest
 
+    steps:
+    - name: Check Repo
+      uses: actions/checkout@v2
+
+    - name: Check Coding-Style
+      run: check.sh $(pwd) $(pwd) > coding-style-reports.log
+
+    - name: create annotations and coding style
+      run: |
+        cat coding-style-reports.log | while read line; do
+          file=$(echo $line | awk -F: '{print $1}')
+          line_number=$(echo $line | awk -F: '{print $2}')
+          error_message=$(echo $line | awk -F: '{print $3}')
+          echo "::error file=$file,line=$line_number::${error_message}"
+        done
+
+    - name: Fail the job if there are coding style errors
+      run: |
+        if grep -q . coding-style-reports.log; then
+          echo "Coding style errors."
+          exit 1
+        else
+          echo "No coding style errors."
+        fi
